---
sudo: false

language: python

python: 2.7

services: docker

install:
  - pip install ansible==2.7.7
  - pip install testinfra molecule docker

before_script:
  - cd ../
  - mv ansible-sbt triviadata.sbt
  - cd triviadata.sbt

script:
  - molecule test
