---
sudo: false

language: python

python: 2.7

services: docker

install:
  - pip install ansible==2.7.7
  - pip install testinfra molecule docker
  - git clone --depth=50 --branch=master https://github.com/${TRAVIS_REPO_SLUG}.git triviadata.sbt
  - cd triviadata.sbt

script:
  - molecule test
